# Generated by Django 4.1 on 2022-08-28 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_authors_book_authors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authors',
            new_name='Author',
        ),
    ]
